import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'About Section',
    description: 'Generated by create next app',
}
export default function AboutLayout({ children }) {
    return (
        <div>
            <h1>about section</h1>
            {children}
        </div>

    )
}